// import "../../styles/globals.css";
import { ReactNode } from "react";
// import KeycloakWrapper from "@/lib/keycloakWrapper";

export const metadata = {
  title: "RAG App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Keycloak authentication temporarily disabled. */}
        {children}
      </body>
    </html>
  );
}
